services:
    _defaults:
        public: false

    VisualCraft\Bundle\MailerBundle\SwiftMailerProvider\LazySwiftMailerProvider:
        arguments: [ '@service_container', '%swiftmailer.mailers%', '%swiftmailer.default_mailer%' ]

    visual_craft_mailer.swift_mailer_provider.lazy:
        alias: VisualCraft\Bundle\MailerBundle\SwiftMailerProvider\LazySwiftMailerProvider

    VisualCraft\Bundle\MailerBundle\SwiftMailerProvider\SwiftMailerProviderInterface:
        alias: VisualCraft\Bundle\MailerBundle\SwiftMailerProvider\LazySwiftMailerProvider

    VisualCraft\Bundle\MailerBundle\MailTypeRegistry\LazyMailTypeRegistry: ~

    visual_craft_mailer.mail_type_registry.lazy:
        alias: VisualCraft\Bundle\MailerBundle\MailTypeRegistry\LazyMailTypeRegistry

    VisualCraft\Bundle\MailerBundle\MailTypeRegistry\MailTypeRegistryInterface:
        alias: VisualCraft\Bundle\MailerBundle\MailTypeRegistry\LazyMailTypeRegistry

    VisualCraft\Bundle\MailerBundle\MessageFactory\MessageFactory:
        arguments: ['@VisualCraft\Bundle\MailerBundle\MailTypeRegistry\MailTypeRegistryInterface']

    VisualCraft\Bundle\MailerBundle\MessageFactory\MessageFactoryInterface:
        alias: VisualCraft\Bundle\MailerBundle\MessageFactory\MessageFactory

    VisualCraft\Bundle\MailerBundle\Mailer:
        arguments:
            - '@VisualCraft\Bundle\MailerBundle\SwiftMailerProvider\SwiftMailerProviderInterface'
            - '@VisualCraft\Bundle\MailerBundle\MessageFactory\MessageFactoryInterface'

    visual_craft_mailer.mailer:
        alias: VisualCraft\Bundle\MailerBundle\Mailer
